# Generated by Django 3.1.5 on 2021-01-30 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourses',
            old_name='year_in_school',
            new_name='courseWork',
        ),
    ]
